{
 "title": "Container Health",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "task",
    "label": "Tasks",
    "query": "label_values(container_label_com_docker_swarm_service_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Containers Running",
   "type": "graph",
   "gridPos": { "h": 4, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_com_docker_swarm_service_name=~\"${task:pipe}\"})"
    }
   ]
  },
  {
   "title": "Swarm Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_boot_time_seconds)" }
   ]
  },
  {
   "title": "Swarm Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes)"
    }
   ]
  },
  {
   "title": "Swarm Cores",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(machine_cpu_cores)" }
   ]
  },
  {
   "title": "Container Single Core Utilisation",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"${task:pipe}\"}[15s])) by (host, container_label_com_docker_swarm_service_name, container_label_com_docker_swarm_task_name)",
     "legendFormat": "{{host}}-{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Container CPU Utilisation by Service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"${task:pipe}\"}[15s])) by (container_label_com_docker_swarm_service_name)",
     "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total CPUs" },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[15s]))",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Container CPU Utilisation by Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"${task:pipe}\"}[15s])) by (container_label_com_docker_stack_namespace)",
     "legendFormat": "{{container_label_com_docker_stack_namespace}}"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total CPUs" },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[15s]))",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Container CPU Utilisation by Host",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_service_name=~\"${task:pipe}\"}[15s])) by (host)",
     "legendFormat": "{{host}}"
    },
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total CPUs" },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[15s]))",
     "legendFormat": "Total CPU Usage"
    }
   ]
  },
  {
   "title": "Container Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"${task:pipe}\"}",
     "legendFormat": "{{host}}-{{container_label_com_docker_swarm_service_name}}"
    }
   ]
  },
  {
   "title": "Container CPU Utilisation by Stack",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container_label_com_docker_swarm_service_name=~\"${task:pipe}\"}) by (container_label_com_docker_stack_namespace)",
     "legendFormat": "{{container_label_com_docker_stack_namespace}}"
    },
    { "expr": "sum(machine_memory_bytes)", "legendFormat": "Total RAM" },
    {
     "expr": "sum(machine_memory_bytes)-sum(node_memory_MemAvailable_bytes)",
     "legendFormat": "Total RAM Usage"
    }
   ]
  }
 ]
}