{
 "title": "Swarm Scale",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Cluster Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(node_load1 / on (host) machine_cpu_cores)",
     "legendFormat": "1 Minute Load"
    },
    {
     "expr": "avg(node_load15 / on (host) machine_cpu_cores)",
     "legendFormat": "15 Minute Load"
    }
   ]
  },
  {
   "title": "CPU Time Per Second",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "CPU Time Per Second" }
   ],
   "targets": [
    { "expr": "sum(machine_cpu_cores)", "legendFormat": "Total CPU Limit" },
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[1m]))",
     "legendFormat": "Total CPU Utalization"
    },
    { "expr": "sum(node_load1)", "legendFormat": "Estimated Required CPU" }
   ]
  },
  {
   "title": "Running Container Count",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(container_last_seen{container_label_com_docker_swarm_task_name!=\"\"})",
     "legendFormat": "Container Count"
    }
   ]
  }
 ]
}